services:
  - type: web
    name: ticketflow
    runtime: node
    buildCommand: |
      npm install
      npm run build:css
      npm run build
      composer install --no-dev --optimize-autoloader --working-dir=.
    startCommand: npm start
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: NODE_ENV
        value: production